"""MLP-based classifier for embeddings.

This module provides a simple MLP classifier and training utilities
for classifying embeddings generated by `get_embedding_from_raw`.
"""

from typing import Dict, Iterable, List, Sequence, Tuple

import numpy as np
import torch
from torch import nn
from torch.utils.data import DataLoader, Dataset, WeightedRandomSampler
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score


class EmbeddingDataset(Dataset):
    """Dataset wrapping pre-computed embeddings and labels."""

    def __init__(self, embeddings: Sequence[np.ndarray], labels: Sequence[int]):
        self.embeddings = [torch.tensor(e, dtype=torch.float32) for e in embeddings]
        self.labels = torch.tensor(labels, dtype=torch.long)

    def __len__(self) -> int:  # type: ignore[override]
        return len(self.labels)

    def __getitem__(self, idx: int) -> Tuple[torch.Tensor, torch.Tensor]:  # type: ignore[override]
        return self.embeddings[idx], self.labels[idx]


class MLPClassifier(nn.Module):
    def __init__(
        self,
        input_dim: int,
        num_classes: int,
        hidden_dims: Iterable[int] = (256, 128),
        dropout: float = 0.1,
    ):
        """Simple fully connected network for classification."""
        super().__init__()
        layers: List[nn.Module] = []
        prev_dim = input_dim
        for h in hidden_dims:
            layers.append(nn.Linear(prev_dim, h))
            layers.append(nn.ReLU())
            layers.append(nn.Dropout(dropout))
            prev_dim = h
        self.feature_extractor = nn.Sequential(*layers)
        self.fc_out = nn.Linear(prev_dim, num_classes)

    def forward(self, x: torch.Tensor) -> torch.Tensor:  # type: ignore[override]
        x = self.feature_extractor(x)
        return self.fc_out(x)


def evaluate_metrics(
    model: nn.Module,
    embeddings: Sequence[np.ndarray],
    labels: Sequence[int],
    criterion: nn.Module,
    batch_size: int = 32,
    device: torch.device | None = None,
) -> Dict[str, float]:
    """Compute loss, accuracy, F1 and AUC for a dataset."""
    if device is None:
        device = next(model.parameters()).device
    dataset = EmbeddingDataset(embeddings, labels)
    dataloader = DataLoader(dataset, batch_size=batch_size)
    model.eval()
    total_loss = 0.0
    all_probs: List[np.ndarray] = []
    all_labels: List[int] = []
    with torch.no_grad():
        for x, y in dataloader:
            x = x.to(device)
            y = y.to(device)
            logits = model(x)
            loss = criterion(logits, y)
            probs = torch.softmax(logits, dim=1)
            total_loss += loss.item() * x.size(0)
            all_probs.append(probs.cpu().numpy())
            all_labels.extend(y.cpu().numpy().tolist())

    all_probs_np = np.concatenate(all_probs, axis=0)
    all_labels_np = np.array(all_labels)
    preds = all_probs_np.argmax(axis=1)
    acc = accuracy_score(all_labels_np, preds)
    f1 = f1_score(all_labels_np, preds, average="macro")
    try:
        auc = roc_auc_score(all_labels_np, all_probs_np, multi_class="ovr")
    except ValueError:
        auc = float("nan")
    avg_loss = total_loss / len(dataset)
    return {"loss": avg_loss, "acc": acc, "f1": f1, "auc": auc}


def train_mlp_classifier(
    train_embeddings: Sequence[np.ndarray],
    train_labels: Sequence[int],
    num_classes: int,
    val_embeddings: Sequence[np.ndarray] | None = None,
    val_labels: Sequence[int] | None = None,
    hidden_dims: Iterable[int] = (256, 128),
    dropout: float = 0.1,
    lr: float = 1e-3,
    epochs: int = 10,
    batch_size: int = 32,
    device: torch.device | None = None,
    use_class_weights: bool = True,
    use_weighted_sampler: bool = True,
) -> MLPClassifier:
    """Train an MLP classifier from pre-computed embeddings.

    When ``use_class_weights`` is ``True`` the cross entropy loss is weighted
    inversely proportional to class frequencies. If ``use_weighted_sampler`` is
    ``True`` the dataloader uses :class:`WeightedRandomSampler` so that each
    class is sampled with approximately equal probability.
    """

    if device is None:
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    input_dim = int(np.array(train_embeddings[0]).shape[0])
    model = MLPClassifier(
        input_dim=input_dim,
        num_classes=num_classes,
        hidden_dims=hidden_dims,
        dropout=dropout,
    ).to(device)

    dataset = EmbeddingDataset(train_embeddings, train_labels)

    class_counts = np.bincount(train_labels, minlength=num_classes)
    class_weights = 1.0 / np.maximum(class_counts, 1)
    if use_weighted_sampler:
        sample_weights = [class_weights[label] for label in train_labels]
        sampler = WeightedRandomSampler(sample_weights, num_samples=len(sample_weights), replacement=True)
        dataloader = DataLoader(dataset, batch_size=batch_size, sampler=sampler)
    else:
        dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    if use_class_weights:
        weight_tensor = torch.tensor(class_weights, dtype=torch.float32).to(device)
        criterion = nn.CrossEntropyLoss(weight=weight_tensor)
    else:
        criterion = nn.CrossEntropyLoss()

    for epoch in range(1, epochs + 1):
        model.train()
        for x, y in dataloader:
            x = x.to(device)
            y = y.to(device)
            optimizer.zero_grad()
            logits = model(x)
            loss = criterion(logits, y)
            loss.backward()
            optimizer.step()

        train_metrics = evaluate_metrics(
            model,
            train_embeddings,
            train_labels,
            criterion,
            batch_size=batch_size,
            device=device,
        )
        msg = (
            f"Epoch {epoch}/{epochs} - train_loss: {train_metrics['loss']:.4f}, "
            f"train_acc: {train_metrics['acc']:.4f}, "
            f"train_f1: {train_metrics['f1']:.4f}, "
            f"train_auc: {train_metrics['auc']:.4f}"
        )
        if val_embeddings is not None and val_labels is not None:
            val_metrics = evaluate_metrics(
                model,
                val_embeddings,
                val_labels,
                criterion,
                batch_size=batch_size,
                device=device,
            )
            msg += (
                f", val_loss: {val_metrics['loss']:.4f}, "
                f"val_acc: {val_metrics['acc']:.4f}, "
                f"val_f1: {val_metrics['f1']:.4f}, "
                f"val_auc: {val_metrics['auc']:.4f}"
            )
        print(msg)

    return model


if __name__ == "__main__":
    print(
        "This module provides utilities for training an MLP classifier on embeddings."
    )
